name: relative
favicon: null
layout_spectrum: 0.39104135637171566
typography_spectrum: 0.6302115914877504
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6721194349229336
  lightness: 0.4814809209201485
  saturation: 0.19412391493096948
  rhythmicContrast: 0.15780374966561794
purpose: []
